In [248]:
using DataFrames
# read in the fifa 18 dataset
dataset = readtable("../data/CompleteDataset.csv")

df = DataFrame(dataset)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] #readtable#233(::Bool, ::Char, ::Array{Char,1}, ::Char, ::Array{String,1}, ::Array{String,1}, ::Array{String,1}, ::Bool, ::Int64, ::Array{Symbol,1}, ::Array{Any,1}, ::Bool, ::Char, ::Bool, ::Int64, ::Array{Int64,1}, ::Bool, ::Symbol, ::Bool, ::Bool, ::DataFrames.#readtable, ::String) at /home/adithya/.julia/v0.6/DataFrames/src/deprecated.jl:1050
 [3] readtable(::String) at /home/adithya/.julia/v0.6/DataFrames/src/deprecated.jl:1050
 [4] include_string(::String, ::String) at ./loading.jl:522
 [5] include_string(::Module, ::String, ::String) at /home/adithya/.julia/v0.6/Compat/src/Compat.jl:71
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/adithya/.julia/v0.6/IJulia/src/execute_request.jl:158
 [7] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/adithya/.julia/v0.6/Compat/src/Compat.jl:385
 [8] eventloop(::ZMQ.Socket) at /home/adithya/.julia/v0.6/IJulia/src

17981×75 DataFrames.DataFrame. Omitted printing of 72 columns
│ Row   │ x     │ Name              │ Age │
├───────┼───────┼───────────────────┼─────┤
│ 1     │ 0     │ Cristiano Ronaldo │ 32  │
│ 2     │ 1     │ L. Messi          │ 30  │
│ 3     │ 2     │ Neymar            │ 25  │
│ 4     │ 3     │ L. Suárez         │ 30  │
│ 5     │ 4     │ M. Neuer          │ 31  │
│ 6     │ 5     │ R. Lewandowski    │ 28  │
│ 7     │ 6     │ De Gea            │ 26  │
│ 8     │ 7     │ E. Hazard         │ 26  │
│ 9     │ 8     │ T. Kroos          │ 27  │
│ 10    │ 9     │ G. Higuaín        │ 29  │
│ 11    │ 10    │ Sergio Ramos      │ 31  │
⋮
│ 17970 │ 17969 │ F. Prohart        │ 18  │
│ 17971 │ 17970 │ A. Kilgour        │ 19  │
│ 17972 │ 17971 │ R. White          │ 18  │
│ 17973 │ 17972 │ A. Conway         │ 19  │
│ 17974 │ 17973 │ T. Sawyer         │ 18  │
│ 17975 │ 17974 │ J. Keeble         │ 18  │
│ 17976 │ 17975 │ T. Käßemodel      │ 28  │
│ 17977 │ 17976 │ A. Kelsey         │ 17  │
│ 17978 │ 17977 │ B. Richardson     │ 47  │
│ 17979 │ 17978 │ J. Young          │ 17  │
│ 17980 │ 17979 │ J. Lundstram      │ 18  │
│ 17981 │ 17980 │ L. Sackey         │ 18  │

# Cleaning the Data

In [249]:
## replace missing data for player clubs
for i in 1:nrow(df)
    if ismissing(df[i,9])
       df[i,9] = "No Club"
    end
end

In [250]:
## replace goal keepers missing positions with missing 
for i in 1:nrow(df)
    if(df[i,64] == "GK")
        for j in 1:ncol(df)
            if(ismissing(df[i,j]))
                df[i,j] = 0
            end
        end
    end
end


In [251]:
deleterows!(df,find(x->x == 13771, df[:,1]))

17980×75 DataFrames.DataFrame. Omitted printing of 72 columns
│ Row   │ x     │ Name              │ Age │
├───────┼───────┼───────────────────┼─────┤
│ 1     │ 0     │ Cristiano Ronaldo │ 32  │
│ 2     │ 1     │ L. Messi          │ 30  │
│ 3     │ 2     │ Neymar            │ 25  │
│ 4     │ 3     │ L. Suárez         │ 30  │
│ 5     │ 4     │ M. Neuer          │ 31  │
│ 6     │ 5     │ R. Lewandowski    │ 28  │
│ 7     │ 6     │ De Gea            │ 26  │
│ 8     │ 7     │ E. Hazard         │ 26  │
│ 9     │ 8     │ T. Kroos          │ 27  │
│ 10    │ 9     │ G. Higuaín        │ 29  │
│ 11    │ 10    │ Sergio Ramos      │ 31  │
⋮
│ 17969 │ 17969 │ F. Prohart        │ 18  │
│ 17970 │ 17970 │ A. Kilgour        │ 19  │
│ 17971 │ 17971 │ R. White          │ 18  │
│ 17972 │ 17972 │ A. Conway         │ 19  │
│ 17973 │ 17973 │ T. Sawyer         │ 18  │
│ 17974 │ 17974 │ J. Keeble         │ 18  │
│ 17975 │ 17975 │ T. Käßemodel      │ 28  │
│ 17976 │ 17976 │ A. Kelsey         │ 17  │
│ 17977 │ 17977 │ B. Richardson     │ 47  │
│ 17978 │ 17978 │ J. Young          │ 17  │
│ 17979 │ 17979 │ J. Lundstram      │ 18  │
│ 17980 │ 17980 │ L. Sackey         │ 18  │

Let us say we are the manager of a mid-table team in the premier league. As such a team, we are faced with more difficult decisions than that of an upper table team such as Chelsea or Manchester United. We may not have access to the best supoprt staff or money or attract players with great skill. Here, we will assume the role of manager of Southampton. They placed in 8th position in the Premier League in 2016-17 season with 46 points. 

# Defining Functions

In [252]:
# extract all premier league teams in 2016-17
teams = ["Chelsea","Tottenham Hotspur","Manchester City","Liverpool","Arsenal","Manchester United",
    "Everton","Southampton","Bournemouth","West Bromwich Albion","West Ham United","Leicester City",
    "Stoke City", "Crystal Palace","Swansea City","Burnley","Watford","Hull City","Middlesbrough","Sunderland"]

# select my team
my_team = "Liverpool"

"Liverpool"

In [253]:
## narrow down the dataset to only teams in the premier league(defined in the teams variable)

premierLeagueTeamPlayerIndices = []

for i in 1:nrow(df)
#     println(i)
    if in(df[i, 9],teams) == true
        push!(premierLeagueTeamPlayerIndices, i) ## add this index into our array
    end
end

premierLeagueTeamPlayers = df[premierLeagueTeamPlayerIndices,:]

# from the players in the premier league, obtain players for my team
myteamPlayers = premierLeagueTeamPlayers[premierLeagueTeamPlayers[:,9] .== my_team,:]

31×75 DataFrames.DataFrame. Omitted printing of 72 columns
│ Row │ x     │ Name                │ Age │
├─────┼───────┼─────────────────────┼─────┤
│ 1   │ 54    │ Coutinho            │ 25  │
│ 2   │ 97    │ S. Mané             │ 25  │
│ 3   │ 137   │ M. Salah            │ 25  │
│ 4   │ 145   │ Roberto Firmino     │ 25  │
│ 5   │ 151   │ J. Matip            │ 25  │
│ 6   │ 171   │ A. Lallana          │ 29  │
│ 7   │ 248   │ N. Clyne            │ 26  │
│ 8   │ 261   │ J. Henderson        │ 27  │
│ 9   │ 267   │ G. Wijnaldum        │ 26  │
│ 10  │ 278   │ D. Sturridge        │ 27  │
│ 11  │ 339   │ D. Lovren           │ 27  │
⋮
│ 20  │ 1946  │ A. Robertson        │ 23  │
│ 21  │ 4536  │ M. Grujić           │ 21  │
│ 22  │ 4867  │ D. Solanke          │ 19  │
│ 23  │ 4892  │ A. Bogdán           │ 29  │
│ 24  │ 4911  │ J. Flanagan         │ 24  │
│ 25  │ 5120  │ J. Gomez            │ 20  │
│ 26  │ 5300  │ D. Ward             │ 24  │
│ 27  │ 5808  │ C. Brannagan        │ 21  │
│ 28  │ 6160  │ T. Alexander-Arnold │ 18  │
│ 29  │ 9690  │ O. Ejaria           │ 19  │
│ 30  │ 10726 │ B. Woodburn         │ 17  │
│ 31  │ 12876 │ L. Jones            │ 21  │

## Construct best possible squad 

In [254]:
## the following function will take your existing squad and optimize it to be the best it can be for a given game
## For sake of simplicity, we will assume that every team always plays the regular (and debatably effective) 4-3-3 formation. 
## This involves 4 defenders, 3 midfielders and 3 strikers

# returns a sparse matrix indicating player positions
# takes as input the dataframe of your team (eg: Southampton)
positions_labels = ["ST","LW","RW","GK","CDM","CM","CB","RM","CAM","LM","LB","CF","RB","RWB","LWB"]

function createSquadPosition(team_df)
    positionsMatrix = Array{Int}(nrow(team_df),length(positions_labels)) # initialize an array to hold positions
    for i in 1:nrow(team_df)
        preferredPos =  split(lstrip(rstrip(team_df[i, 64])))
        positionsMatrix[i,:] = 0
        for j in 1:length(preferredPos) # locate the position definition
            f(x) = x .== preferredPos[j]
            positionsMatrix[i,find(f, positions_labels)[1]] = 1
        end
    end
    return positionsMatrix
end


using JuMP, Cbc

squad = myteamPlayers
positions = createSquadPosition(squad) # get preferred positions of each player (returns a sparse matrix)
formation = [1,1,1,1,2,1,2,0,0,0,1,0,1,0,0] # 4-3-3 formation
overall = squad[:,7]

m = Model(solver=CbcSolver())
@variable(m, my_squad[1:nrow(squad)], Bin) # create a variable to hold 33 players
@variable(m, position_preference[1:nrow(squad),1:length(positions_labels)], Bin) # holds player preference positions

# constraint to pick preferred player
for j in 1:length(formation)
    @constraint(m, sum(positions[i,j]*(position_preference[i,j]) for i in 1:nrow(squad)) == formation[j])
end

#constraint to ensure that only one player is picked per position
for j in 1:nrow(squad)
    @constraint(m,  0 <= sum(position_preference[j,:]) <= 1)
end

# constraint to ensure that only 11 players are picked in a team
@constraint(m, sum(position_preference) == 11)

# maximize the overall team rating 
@objective(m, Max, sum(sum(position_preference[i,:])*overall[i] for i in 1:nrow(squad)))
solve(m)

selection = []
for i in 1:nrow(squad)
    if(sum(getvalue(position_preference)[i,:]) == 1)
        push!(selection, i)
    end
end
squad[selection,:]


11×75 DataFrames.DataFrame. Omitted printing of 72 columns
│ Row │ x   │ Name            │ Age │
├─────┼─────┼─────────────────┼─────┤
│ 1   │ 54  │ Coutinho        │ 25  │
│ 2   │ 97  │ S. Mané         │ 25  │
│ 3   │ 145 │ Roberto Firmino │ 25  │
│ 4   │ 151 │ J. Matip        │ 25  │
│ 5   │ 171 │ A. Lallana      │ 29  │
│ 6   │ 248 │ N. Clyne        │ 26  │
│ 7   │ 261 │ J. Henderson    │ 27  │
│ 8   │ 339 │ D. Lovren       │ 27  │
│ 9   │ 372 │ S. Mignolet     │ 29  │
│ 10  │ 408 │ E. Can          │ 23  │
│ 11  │ 509 │ J. Milner       │ 31  │

In [184]:
println("Average team rating for ", my_team, " = ", getobjectivevalue(m)/11)

Average team rating for Arsenal = 84.0


In [225]:
squad[find(x->x == 1, getvalue(position_preference[:,13])),2]

1-element Array{Union{Missings.Missing, String},1}:
 "N. Clyne"

In [150]:
positions_labels

15-element Array{String,1}:
 "ST" 
 "LW" 
 "RW" 
 "GK" 
 "CDM"
 "CM" 
 "CB" 
 "RM" 
 "CAM"
 "LM" 
 "LB" 
 "CF" 
 "RB" 
 "RWB"
 "LWB"

## Team Chemistry

In [255]:

function createChemistryMatrix(squad)
    nationality = squad[:,5]
    
    chemistryMatrix = Array{Int}(nrow(squad),nrow(squad))
    for i in 1:length(nationality)
        chemistryMatrix[i,:] = 0
        chemistryMatrix[i,find(x -> x == nationality[i], nationality)] = 1
    end
    return chemistryMatrix
end
createChemistryMatrix(squad)

31×31 Array{Int64,2}:
 1  0  0  1  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  1  1  0  1  0  0  0  …  0  0  1  0  1  1  0  1  1  1  0  1
 0  0  0  0  0  1  1  1  0  1  0  0  0     0  0  1  0  1  1  0  1  1  1  0  1
 0  0  0  0  0  1  1  1  0  1  0  0  0     0  0  1  0  1  1  0  1  1  1  0  1
 0  0  0  0  0  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  1  1  0  1  0  0  0     0  0  1  0  1  1  0  1  1  1  0  1
 0  0  0  0  0  0  0  0  0  0  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  1    

In [256]:
using JuMP, Cbc

# obtain our squad of players and set their formations
squad = myteamPlayers
positions = createSquadPosition(squad) # get preferred positions of each player (returns a sparse matrix)
formation = [1,1,1,1,2,1,2,0,0,0,1,0,1,0,0] # 4-3-3 formation
overall = squad[:,7]

#incidence matrix for 4-3-3 formation
# it tells us which position links up with which other position
# in the 4-3-3 formation. The neighboring players
# that a certain player links up with determines the chemistry
# at that position


linkups = [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
             1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 
             1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 
             0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
             0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 
             0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
             0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 
             0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 0 
             0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 
             0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 
             0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 
             0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 
             0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
             0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
             0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
             0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
             0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                    
chemistry = createChemistryMatrix(squad)
# for positions in the formation array that have more than 2 players,
# they are in reality two different positions that perform the same function 
# and hence can be performed by players in the same region

# find positions with more than one player
duplicates = find(x-> x > 1, formation)
clone_columns = [] #  store the columns pertaining to the duplicate positions
# clone the columns of the duplicates to the right.
duplicate_col_pos = length(positions_labels)+1
for i in 1:length(duplicates)
    dupcol = []
    # repeat for formation[j]-1 times
    for j in 1:(formation[duplicates[i]] - 1)
        positions = hcat(positions, positions[:,duplicates[i]])
        push!(dupcol, duplicate_col_pos) # push this new column index
        duplicate_col_pos = duplicate_col_pos+1
    end
    push!(clone_columns, dupcol)
end
        

In [292]:
# create a model
m = Model(solver=CbcSolver())

@variable(m, position_preference[1:nrow(squad),1:size(positions)[2]], Bin) # holds player preference positions


# constraint to pick preferred player
for j in 1:length(formation) # now that we have split columns to identify unique positions, we each positionw ill sum up to be 1
    if formation[j] == 0 #if there are no players in a position, then make sure that the sum of that column is 0
        @constraint(m, sum(positions[i,j]*(position_preference[i,j]) for i in 1:nrow(squad)) == 0)
    else
        @constraint(m, sum(positions[i,j]*(position_preference[i,j]) for i in 1:nrow(squad)) == 1)
    end
end

# deal with multiple positions
# clone_columns and duplicates have the same size
for i in 1:length(clone_columns)
    
    # ensure that the sum of each clone column is 1, since each position is now treated as unique
    for j in 1:length(clone_columns[i])
        @constraint(m, sum(positions[k,clone_columns[i][j]]*(position_preference[k,clone_columns[i][j]]) for k in 1:nrow(squad)) == 1)
    end
    # ensure that the colsums of the clones and the original columns is equal to the number of occurances of that position in the formation vector
    @constraint(m, sum(position_preference[:, duplicates[i]]) +
            sum(sum(position_preference[:, clone_columns[i][k]]) for k in 1:length(clone_columns[i]))  
     == formation[duplicates[i]])
    
end



#constraint to ensure that only one player is picked per position
for j in 1:nrow(squad)
    @constraint(m,  0 <= sum(position_preference[j,:]) <= 1)
end

# constraint to ensure that only 11 players are picked in a team
@constraint(m, sum(position_preference) == 11)
lambda = 0.000001;
# maximize the0 overall team rating 
@objective(m, Max,
    sum(sum(position_preference[i,:])*overall[i] for i in 1:nrow(squad)) +
    vecdot((lambda*chemistry*position_preference*linkups)*ones(size(linkups)[1]),overall))

solve(m)

selection = []
for i in 1:nrow(squad)
    if(sum(getvalue(position_preference)[i,:]) == 1)
        push!(selection, i)
    end
end
squad[selection,:]

11×75 DataFrames.DataFrame. Omitted printing of 72 columns
│ Row │ x   │ Name            │ Age │
├─────┼─────┼─────────────────┼─────┤
│ 1   │ 54  │ Coutinho        │ 25  │
│ 2   │ 97  │ S. Mané         │ 25  │
│ 3   │ 145 │ Roberto Firmino │ 25  │
│ 4   │ 151 │ J. Matip        │ 25  │
│ 5   │ 171 │ A. Lallana      │ 29  │
│ 6   │ 248 │ N. Clyne        │ 26  │
│ 7   │ 261 │ J. Henderson    │ 27  │
│ 8   │ 339 │ D. Lovren       │ 27  │
│ 9   │ 372 │ S. Mignolet     │ 29  │
│ 10  │ 408 │ E. Can          │ 23  │
│ 11  │ 509 │ J. Milner       │ 31  │

In [271]:
squad[find(x->x == 1, getvalue(position_preference[:,17])),2]

1-element Array{Union{Missings.Missing, String},1}:
 "J. Matip"

15-element Array{String,1}:
 "ST" 
 "LW" 
 "RW" 
 "GK" 
 "CDM"
 "CM" 
 "CB" 
 "RM" 
 "CAM"
 "LM" 
 "LB" 
 "CF" 
 "RB" 
 "RWB"
 "LWB"